name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env: 
          NEXT_PUBLIC_API_BASE_URL=: "https://mba-devstore-apigit.vercel.app"
          APP_URL: "http://localhost:3000"
        with:
          build: npm run build
          start: npm start